---
# Apache httpd configuration tasks

- name: Configure apache httpd
  ansible.builtin.template:
    src: httpd.conf.j2
    dest: "{{ apache_httpd_config_file_path }}"
    mode: 0644
  notify: apache restart

- name: Setup logrotate configuration file
  ansible.builtin.template:
    src: logrotate.j2
    dest: "{{ apache_logrotate_config_path }}"
    mode: 0644
  when: apache_logrotate_config_path | default("") | length > 0