---

- name: Setup apache
  block:
    - include_tasks: modules.yml
    - include_tasks: dirs.yml
    - include_tasks: configure.yml
    - include_tasks: ssl.yml
    - include_tasks: welcome.yml
    - include_tasks: service.yml
  vars:
    apache_modules_managed: >-
      {{ (apache_modules
         + ((apache_modules_load_from_hostvars)
            | ternary(apache_modules_hostvars
                      | default([])
                      | flatten,
                      []))) | unique }}
  tags:
    - role::apache
