---
# Apache modules setup tasks

- name: Install desired apache modules
  ansible.builtin.include_role:
    name: amtega.packages
  when: apache_modules_managed | length > 0
  vars:
    packages_os: "{{ lookup('template', 'modules.yml.j2') | from_yaml }}"
    packages_os_notify:
      - apache restart