---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  tasks:

    - name: Force handlers execution
      ansible.builtin.meta: flush_handlers

    - name: Check that apache is listening
      ansible.builtin.wait_for:
        port: "{{ item }}"
        timeout: 10
      loop:
        - "{{ apache_httpd_port }}"
        - "{{ apache_ssl_port }}"

    - name: Check that http port returns welcome page
      ansible.builtin.uri:
        url: "http://localhost:{{ apache_httpd_port }}/ansible_welcome.html"
        return_content: yes
      register: check_httpd_result
      failed_when: >-
         not check_httpd_result.content
             is search("Apache Web Server was installed by ansible")

    - name: Check that ssl port returns welcome page
      ansible.builtin.uri:
        url: "https://localhost:{{ apache_ssl_port }}/ansible_welcome.html"
        return_content: yes
        validate_certs: no
      register: check_ssl_result
      failed_when: >-
         not check_ssl_result.content
             is search("Apache Web Server was installed by ansible")

    - name: Register apache apache apache modueles
      ansible.builtin.command: "/usr/sbin/httpd -M"
      changed_when: no
      register: apache_read_modules_installed

    - name: Ensure apache modules are loaded
      ansible.builtin.assert:
        that:
          - apache_read_modules_installed.stdout is search("ssl_module")
          - apache_read_modules_installed.stdout is search("ldap_module")